# Credenciales del Proyecto SonarCloud Oficial
sonar.projectKey=conectani_Proyecto-Tani
sonar.organization=conectani
sonar.projectName=Proyecto-Tani

# Configuración de Rutas de Código
sonar.sources=app,utils
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Vinculación de Cobertura Istanbul / LCOV
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Tipos de Codificación y Exclusiones de Archivos
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**,dist/**,.expo/**,scripts/**,assets/**
sonar.cpd.exclusions=**/*
