# Credenciales del Proyecto SonarCloud Oficial
sonar.projectKey=conectani_Proyecto-Tani
sonar.organization=conectani
sonar.projectName=Proyecto-Tani

# Configuración de Rutas de Código
sonar.sources=app,utils
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Vinculación de Cobertura Istanbul / LCOV
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Tipos de Codificación y Exclusiones de Archivos
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**,app/_layout.tsx,**/*.sql,**/*.pdf,**/dist/**,**/.expo/**,**/assets/**
sonar.cpd.exclusions=**/*.sql,**/__tests__/**,**/assets/**,app/_layout.tsx,app/politica.tsx,app/terminos.tsx,app/notificaciones.tsx,components/ui/**
