# Credenciales del Proyecto
sonar.projectKey=UTP_connectani-mobile
sonar.organization=utp-herramientas-desarrollo-2026
sonar.projectName=ConnecTani Mobile

# Configuración de Rutas de Código
sonar.sources=app,utils
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Vinculación de Cobertura Istanbul / LCOV
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Tipos de Codificación de Archivos
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**,app/_layout.tsx
