name: ConnecTani DevSecOps Pipeline

on:
  pull_request:
    branches: [ "develop", "main" ]
  push:
    branches: [ "develop", "main" ]

jobs:
  build-and-qa-app:
    name: QA App Beneficiarios (ConnecTani)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Proyecto-tani

    steps:
    - name: 1. Checkout del Codigo Fuente
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: 2. Configurar Node.js (v20)
      uses: actions/setup-node@39370e3970a6d050c08020d81da5e2d6675276e0 # v4.1.0
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/Proyecto-tani/package-lock.json

    - name: 3. Instalar Dependencias del Entorno
      run: npm ci --ignore-scripts

    - name: 4. Ejecutar Pruebas Automatizadas (Jest & Cobertura Istanbul)
      run: npm run test

    - name: 5. Analisis de Calidad de Codigo (SonarCloud)
      uses: SonarSource/sonarcloud-github-action@e4425d48a609d57a26f633190dfebccdbba0401d
      continue-on-error: true
      with:
        projectBaseDir: src/Proyecto-tani
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: 6. Analisis de Seguridad de Dependencias (Snyk SCA)
      uses: snyk/actions/node@806182742461562b67788a64410098c9d9b96dba
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        directory: src/Proyecto-tani

  build-and-qa-admin:
    name: QA App Administrador (Tani Admin)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Proyecto-tani-admin

    steps:
    - name: 1. Checkout del Codigo Fuente
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: 2. Configurar Node.js (v20)
      uses: actions/setup-node@39370e3970a6d050c08020d81da5e2d6675276e0 # v4.1.0
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/Proyecto-tani-admin/package-lock.json

    - name: 3. Instalar Dependencias del Entorno
      run: npm ci --ignore-scripts

    - name: 4. Ejecutar Control de Estilo (ESLint)
      run: npm run lint

    - name: 5. Analisis de Seguridad de Dependencias (Snyk SCA)
      uses: snyk/actions/node@806182742461562b67788a64410098c9d9b96dba
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        directory: src/Proyecto-tani-admin


  deploy-to-azure-container-ops:
    name: Despliegue Continuo (CD a Azure Container Registry & Web App)
    needs: build-and-qa-app
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Proyecto-tani
    steps:
    - name: 1. Checkout del Codigo Fuente
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: 2. Autenticacion en Azure Container Registry (ACR)
      uses: azure/docker-login@16198f1f496739665c36142144ef20b70d76bfcd # v2
      continue-on-error: false
      with:
        login-server: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: 3. Construccion de Imagen Docker Multi-etapa
      env:
        AZURE_ACR_SERVER: ${{ secrets.AZURE_ACR_SERVER }}
      run: docker build -t "$AZURE_ACR_SERVER/tani-app:${{ github.sha }}" .

    - name: 4. Publicacion de Imagen en Registro de Azure (Push to ACR)
      continue-on-error: false
      env:
        AZURE_ACR_SERVER: ${{ secrets.AZURE_ACR_SERVER }}
      run: docker push "$AZURE_ACR_SERVER/tani-app:${{ github.sha }}"

    - name: 5. Despliegue Continuo en Azure App Service for Containers
      uses: azure/webapps-deploy@81729dd7bbef60b3724c965b93198ae4a29a0665 # v3
      continue-on-error: false
      with:
        app-name: 'connectani-app-service'
        images: '${{ secrets.AZURE_ACR_SERVER }}/tani-app:${{ github.sha }}'

